### ISSUE TITLE
IBP 2.5 Installation errors

### ISSUE THREAD

**Issue by amontero0611** [ibm-cloud-docs/blockchain-sw-25#2]
I found these issues when following the IBP installation procedure on OCP documented [here](https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-deploy-ocp):

1)
ibmuser@ubuntu:~/ibp$ kubectl get secret webhook-tls-cert -n ibpinfra -o json | jq -r .data.\"cert.pem\"
**Error from server (NotFound): secrets "webhook-tls-cert" not found**

2) After changing the previous command to use docker-key-secret instead of webhook-tls-cert I found:
ibmuser@ubuntu:~/ibp$ kubectl get secret docker-key-secret -n ibpinfra -o json | jq -r .data.\"cert.pem\"
**null**

3) kubectl apply -f ibpca-crd.yaml
**Error from server (BadRequest): error when creating "ibpca-crd.yaml": CustomResourceDefinition in version "v1beta1" cannot be handled as a CustomResourceDefinition: v1beta1.CustomResourceDefinition.Spec: v1beta1.CustomResourceDefinitionSpec.Conversion: v1beta1.CustomResourceConversion.WebhookClientConfig: v1beta1.WebhookClientConfig.Service: CABundle: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|DLE\u003e","service"|..., bigger context ...|okClientConfig":{"caBundle":"\u003cCABUNDLE\u003e","service":{"name":"ibp-webhook","namespace":"ibpi|...**

I cannot carry on.

**Comment by pamandrejko** [comment]
@amontero0611 
Thank you for sharing this feedback. 
It appears that the command `kubectl get secret webhook-tls-cert -n ibpinfra -o json | jq -r .data."cert.pem"` is failing because your webhook did not deploy.

The following command would give a little more info:
$ kubectl get pods -n ibpinfra

**Comment by amontero0611** [comment]
Thank you @pamandrejko ,
you're right the webhook did not deploy, security context issues when applying **deployment.yaml** :

**pods "ibp-webhook-fb7d486bc-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1001570000, 1001579999] capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added]**

Can you please let me know how to carry on? Thanks.

**Comment by pamandrejko** [comment]
@amontero0611 Thank you for sharing this.  We are looking into it right now. Can you share what version of OCP you are using?

**Comment by amontero0611** [comment]
I am using the version provided by ROKS, on IBM Cloud:   OpenShift 4.3.23, 
Kubernetes 1.16.2

Saludos / Regards,





Ángel L. Montero Sánchez 
Arquitecto de Industria - Gobierno 
amontero@es.ibm.com 




 




IBM España
Sta. Hortensia 26-28  Madrid 28002 
91-3976611 
http://www.ibm.es

**Comment by pamandrejko** [comment]
@amontero0611 
Can you try the following instructions, we plan to add it to the documentation before you deploy the webhook:


The IBM Blockchain Platform requires specific security and access policies to be added to your project. Copy the security context constraint object below and save it to your local system as `ibp-scc.yaml`.

```yaml
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- NET_BIND_SERVICE
- CHOWN
- DAC_OVERRIDE
- SETGID
- SETUID
- FOWNER
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:authenticated
kind: SecurityContextConstraints
metadata:
  name: ibpinfra
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- "*"
```


After you save the file, run the following commands to add the file to your cluster and add the policy to your project.

```
oc apply -f ibp-scc.yaml -n ibpinfra
oc adm policy add-scc-to-user ibpinfra system:serviceaccounts:ibpinfra
```

If the commands are successful, you can see a response that is similar to the following example:
```
securitycontextconstraints.security.openshift.io/ibpinfra created
scc "ibpinfra" added to: ["system:serviceaccounts:ibpinfra"]
```
Then try to deploy your webhook:
https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-deploy-ocp#webhook-deploy
